login_utility/urls.py
from django.conf.urls import include, url


urlpatterns = [
    # Examples:
    url(r'^$', 'login_utility.views.login_user', name='login_user'),
    url(r'^forget-password/', 'login_utility.views.forget_password', name="forget_password"),
    url(r'^reset-password/(?P<token>[a-zA-Z0-9]*)/$', 'login_utility.views.user_reset_password'),
    
]

login_utility/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


class PasswordResetAuth(models.Model):
    choose_me = models.BooleanField(default=True)
    email = models.EmailField(max_length=75)
    token = models.CharField(max_length=11)

login_utility/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea
from django.utils.translation import gettext as _
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    error_messages = {
        "email_not_exists": _("This email id does not exists.Enter a Valid email-id."),
    }
    email = forms.EmailField(max_length=75)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get("email", "")
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(self.error_messages["email_not_exists"], code="email_not_exists",)
        else:
            user = User.objects.get(email=email)
            cleaned_data["username"] = user.username
        return cleaned_data

class EmailVerifyForm(forms.Form):

    error_messages = {
        "email_not_exists": _("This email id does not exists"),
    }
    email = forms.EmailField(max_length=75)

    def clean(self):
        cleaned_data = super(EmailVerifyForm, self).clean()
        email = cleaned_data.get("email", "")
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(self.error_messages["email_not_exists"], code="email_not_exists",)
        return cleaned_data

class ResetPasswordForm(forms.Form):
    error_messages = {
        "password_match": _("Password did not match."),
    }
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(ResetPasswordForm, self).clean()
        new_password = cleaned_data.get("new_password", "")
        confirm_password = cleaned_data.get("confirm_password", "")
        if new_password != confirm_password:
            raise forms.ValidationError(self.error_messages["password_match"], code="password_match",)
        return cleaned_data

login_utility/views.py
from django.shortcuts import render


from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from django.http import HttpResponse
from django.contrib.sites.models import get_current_site
from django.conf import settings
from django.core.urlresolvers import reverse

from forms import LoginForm, EmailVerifyForm, ResetPasswordForm
from utils import SendEmail
from models import PasswordResetAuth 

def login_user(request):

    if request.user.is_authenticated():
         return redirect(settings.AFTER_LOGIN_REDIRECT_URL)

    form = LoginForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            print "form valid"
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect(settings.AFTER_LOGIN_REDIRECT_URL)

            error_message = "* Invalid password"
            return render_to_response("login/login.html", {
                "form": form,
                "error_message": error_message
            }, context_instance=RequestContext(request))

        return render_to_response("login/login.html", {
            "form": form
        }, context_instance=RequestContext(request))

    return render_to_response("login/login.html", {
        "form": form
    }, context_instance=RequestContext(request))


def forget_password(request):
    if request.user.is_authenticated():
         return redirect(settings.AFTER_LOGIN_REDIRECT_URL)

    form = EmailVerifyForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            email = form.cleaned_data["email"]
            token = get_random_string(length=11)
            password_reset_auth = PasswordResetAuth(choose_me=True, email=email, token=token)
            password_reset_auth.save()
            msg = SendEmail(request=request, file=[])
            msg.send_by_template(
                    recipient=[form.cleaned_data['email']],
                    template_path='login/changepassword_email.html',
                    context={
                        'reset_link': get_current_site(request).domain+"/login/reset-password/{}".format(token)
                    },
                    subject="Reset Password",
                )
            msg = SendEmail(request)
            return redirect("/login/")
    
    return render_to_response("login/forget-password.html", {
        "form":form
    }, context_instance=RequestContext(request))

def user_reset_password(request, token):
    """
        Function is used to reset the password of the user using the token identification
        which was created in forgot password.
    """

    if request.user.is_authenticated():
        return redirect(settings.AFTER_LOGIN_REDIRECT_URL)

    form = ResetPasswordForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            user_auth = get_object_or_404(PasswordResetAuth, token=token)
            user = get_object_or_404(User, email=user_auth.email)

            if user_auth.choose_me is True:
                new_password = form.cleaned_data["new_password"]
                user.set_password(new_password)
                user.save()

                user_auth.choose_me = False
                user_auth.save()
                return redirect("/login/")

            error_message = "* Either you are not an identified user or "\
                "token has been expired. So please click on back."
            return render_to_response("login/reset_password.html", {
                "form": form,
                "error_message": error_message
            }, context_instance=RequestContext(request))

    return render_to_response("login/reset_password.html", {
        "form": form
    }, context_instance=RequestContext(request))

login_utility/templates/login/changepassword_email.html
<a href="{{reset_link}}" >click here</a> to reset password

login_utility/templates/login/forget-password.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href='{% static "css/login_style.css"%}'>


<div id="wrapper">

	<form name="login-form" class="login-form" action="" method="post">
		{% csrf_token%}
		<div class="header">
			<h1>Enter Your Email'ID</h1>
		</div>
	
		<div class="content">
			
			<input style="width:250px;" name="email" type="email" class="input email" id="id_email" placeholder="Email" />
			
			{% if form.emails.errors%}
			<h5 style="color:red">{{ form.emails.errors.as_text}}</h5>
			{% elif form.non_field_errors  %}
			<h5 style="color:red">{{ form.non_field_errors.as_text}}</h5>
			{% endif %}
			
			<div class="user-icon">
			</div>
			
			<div class="pass-icon">
			</div>		
		</div>

		<div class="footer">
			<input type="submit" name="submit" value="Reset" class="button" />
			<a href="/login/">Login</a>
		</div>
	
	</form>

</div>
<div class="gradient">
</div>

login_utility/templates/login/login.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href='{% static "css/login_style.css"%}'>


<div id="wrapper">

	<form name="login-form" class="login-form" action="/login/" method="post">
		{% csrf_token%}
		<div class="header">
			<h1>Login Form</h1>
			<span>Fill out the form below to login to my super awesome imaginary control panel.</span>
		</div>
	
		<div class="content">
			
			<input name="email" type="email" class="input email" id="id_email" placeholder="Email" />
			
			{% if form.emails.errors%}
			<h5 style="color:red">{{ form.emails.errors.as_text}}</h5>
			{% elif form.non_field_errors  %}
			<h5 style="color:red">{{ form.non_field_errors.as_text}}</h5>
			{% endif %}
			
			<div class="user-icon">
			</div>
			
			<input name="password" type="password" class="input password" id="id_password" placeholder="Password" />
			{% if form.password.errors%}
			<h5 style="color:red">{{ form.password.errors.as_text}}</h5>
			{% elif error_message  %}
			<h5 style="color:red">{{ error_message}}</h5>
			{% endif %}
			
			<div class="pass-icon">
			</div>		
		</div>

		<div class="footer">
			<input type="submit" name="submit" value="Login" class="button" />
			<a href="/login/forget-password/">Forget Password</a>
		</div>
	
	</form>

</div>
<div class="gradient">
</div>

login_utility/templates/login/reset_password.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href='{% static "css/login_style.css"%}'>


<div id="wrapper">

	<form name="login-form" class="login-form" action="" method="post">
		{% csrf_token%}
		<div class="header">
			<h1>Enter New Password</h1>
		</div>
	
		<div class="content">
			
			<input style="width:250px;" name="new_password" type="" class="input password" id="id_new_password" placeholder="New Password" />
			
			{% if form.emails.errors%}
				<h5 style="color:red">{{ form.emails.errors.as_text}}</h5>
			{% elif form.non_field_errors  %}
				<h5 style="color:red">{{ form.non_field_errors.as_text}}</h5>
			{% endif %}
			{% if error_message %}
				<h5 style="color:red">{{ error_message }}</h5>
			{% endif %}
				<input style="width:250px;" name="confirm_password" type="" class="input password" id="id_confirm_password" placeholder="Confirm Password" />
				<div class="user-icon">
				</div>

			<div class="pass-icon">
			</div>
		</div>

		<div class="footer">
			<input type="submit" name="submit" value="Submit" class="button" />
		</div>
	
	</form>

</div>
<div class="gradient">
</div>